
"""
Create publication-quality qualitative comparison figures from the
four-panel PNG files generated by the MV-TransUNet evaluation pipeline.

Expected source image layout:
    [Fundus | Ground Truth | Overlay | Prediction]

The script extracts the Fundus, Ground Truth, and Prediction panels from
matching Baseline-128, Baseline-256, and Topology-256 evaluation outputs,
then creates:

Figure 2:
    Dataset | Fundus | Ground Truth | Baseline-128 | Baseline-256 |
    Proposed Topology-256 | Proposed Error Map

Error-map colors:
    Green = true positive
    Red   = false positive
    Blue  = false negative
    Black = true negative

Outputs:
    PNG at 600 dpi
    PDF vector container
    SVG editable vector container

Example:
    python -m src.create_qualitative_figure ^
      --case DRIVE 001 ^
        evaluation_outputs/baseline128_drive/DRIVE_test/comparisons ^
        evaluation_outputs/baseline256_stride128_drive/DRIVE_test/comparisons ^
        evaluation_outputs/topology_drive/DRIVE_test/comparisons ^
      --case STARE 001 ^
        evaluation_outputs/baseline128_stare/STARE_test/comparisons ^
        evaluation_outputs/baseline256_stride128_stare/STARE_test/comparisons ^
        evaluation_outputs/topology_stare/STARE_test/comparisons ^
      --case CHASE_DB1 001 ^
        evaluation_outputs/baseline128_chase/CHASE_DB1_test/comparisons ^
        evaluation_outputs/baseline256_stride128_chase/CHASE_DB1_test/comparisons ^
        evaluation_outputs/topology_chase/CHASE_DB1_test/comparisons ^
      --case HRF 001 ^
        evaluation_outputs/baseline128_hrf/HRF_test/comparisons ^
        evaluation_outputs/baseline256_stride128_hrf/HRF_test/comparisons ^
        evaluation_outputs/topology_hrf/HRF_test/comparisons ^
      --output-dir paper_figures
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image


@dataclass(frozen=True)
class CaseSpecification:
    dataset: str
    case_id: str
    baseline128_dir: Path
    baseline256_dir: Path
    topology_dir: Path


@dataclass(frozen=True)
class ExtractedComparison:
    fundus: np.ndarray
    ground_truth: np.ndarray
    prediction: np.ndarray


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Create a publication-quality qualitative comparison figure "
            "from evaluation comparison strips."
        )
    )

    parser.add_argument(
        "--case",
        action="append",
        nargs=5,
        metavar=(
            "DATASET",
            "CASE_ID",
            "BASELINE128_DIR",
            "BASELINE256_DIR",
            "TOPOLOGY_DIR",
        ),
        required=True,
        help=(
            "Add one dataset case. Repeat this argument for DRIVE, STARE, "
            "CHASE_DB1, and HRF."
        ),
    )

    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("paper_figures"),
        help="Directory where PNG, PDF, and SVG outputs will be saved.",
    )

    parser.add_argument(
        "--threshold",
        type=int,
        default=127,
        help="Binary mask threshold in the range 0-255. Default: 127.",
    )

    parser.add_argument(
        "--title",
        type=str,
        default="Qualitative Comparison Across Retinal Vessel Datasets",
        help="Figure title.",
    )

    return parser.parse_args()


def resolve_case_file(directory: Path, case_id: str) -> Path:
    """
    Resolve a case filename robustly.

    Supports:
        001.png
        001.PNG
        case_001.png
        image_001.png
        any PNG whose stem ends with the case ID
    """
    directory = directory.expanduser().resolve()

    if not directory.exists():
        raise FileNotFoundError(
            f"Comparison directory does not exist: {directory}"
        )

    direct_candidates = [
        directory / f"{case_id}.png",
        directory / f"{case_id}.PNG",
    ]

    for candidate in direct_candidates:
        if candidate.exists():
            return candidate

    png_files = sorted(
        list(directory.glob("*.png"))
        + list(directory.glob("*.PNG"))
    )

    exact_stem_matches = [
        path for path in png_files
        if path.stem == case_id
    ]
    if exact_stem_matches:
        return exact_stem_matches[0]

    suffix_matches = [
        path for path in png_files
        if path.stem.endswith(case_id)
    ]
    if len(suffix_matches) == 1:
        return suffix_matches[0]

    if not png_files:
        raise FileNotFoundError(
            f"No PNG comparison images were found in: {directory}"
        )

    available = ", ".join(path.name for path in png_files[:20])
    raise FileNotFoundError(
        f"Could not identify case '{case_id}' in {directory}. "
        f"Available files include: {available}"
    )


def load_rgb(path: Path) -> np.ndarray:
    with Image.open(path) as image:
        return np.asarray(image.convert("RGB"))


def trim_uniform_borders(
    image: np.ndarray,
    tolerance: int = 3,
) -> np.ndarray:
    """
    Remove thin uniform black/white borders sometimes added during export.
    """
    if image.ndim != 3 or image.shape[2] != 3:
        raise ValueError("Expected an RGB image.")

    gray = image.astype(np.float32).mean(axis=2)

    non_black = gray > tolerance
    non_white = gray < (255 - tolerance)
    informative = non_black & non_white

    rows = np.where(informative.any(axis=1))[0]
    cols = np.where(informative.any(axis=0))[0]

    if rows.size == 0 or cols.size == 0:
        return image

    return image[
        rows[0] : rows[-1] + 1,
        cols[0] : cols[-1] + 1,
    ]


def extract_four_panel_strip(path: Path) -> ExtractedComparison:
    """
    Split an evaluation strip into four equal horizontal panels.

    The evaluation output is expected to follow:
        Fundus | Ground Truth | Overlay | Prediction
    """
    image = load_rgb(path)
    image = trim_uniform_borders(image)

    height, width, _ = image.shape

    if width < 4:
        raise ValueError(
            f"Image is too narrow to contain four panels: {path}"
        )

    panel_width = width // 4
    remainder = width - panel_width * 4

    if remainder > 4:
        raise ValueError(
            f"Comparison strip width ({width}) is not compatible with "
            f"four approximately equal panels: {path}"
        )

    boundaries = [
        0,
        panel_width,
        panel_width * 2,
        panel_width * 3,
        width,
    ]

    panels = [
        image[:, boundaries[index] : boundaries[index + 1]]
        for index in range(4)
    ]

    min_width = min(panel.shape[1] for panel in panels)
    panels = [panel[:, :min_width] for panel in panels]

    return ExtractedComparison(
        fundus=panels[0],
        ground_truth=panels[1],
        prediction=panels[3],
    )


def to_binary_mask(
    image: np.ndarray,
    threshold: int,
) -> np.ndarray:
    """
    Convert a grayscale or RGB vessel visualization into a binary mask.
    """
    if image.ndim == 3:
        gray = (
            0.299 * image[..., 0]
            + 0.587 * image[..., 1]
            + 0.114 * image[..., 2]
        )
    elif image.ndim == 2:
        gray = image
    else:
        raise ValueError(
            f"Unsupported mask shape: {image.shape}"
        )

    return gray >= threshold


def create_error_map(
    ground_truth: np.ndarray,
    prediction: np.ndarray,
    threshold: int,
) -> np.ndarray:
    """
    Build an RGB error map.

    Green = TP
    Red   = FP
    Blue  = FN
    Black = TN
    """
    gt = to_binary_mask(ground_truth, threshold)
    pred = to_binary_mask(prediction, threshold)

    if gt.shape != pred.shape:
        pred_image = Image.fromarray(
            (pred.astype(np.uint8) * 255)
        )
        pred_image = pred_image.resize(
            (gt.shape[1], gt.shape[0]),
            resample=Image.Resampling.NEAREST,
        )
        pred = np.asarray(pred_image) >= threshold

    error = np.zeros(
        (gt.shape[0], gt.shape[1], 3),
        dtype=np.uint8,
    )

    true_positive = gt & pred
    false_positive = (~gt) & pred
    false_negative = gt & (~pred)

    error[true_positive] = [0, 210, 0]
    error[false_positive] = [230, 40, 40]
    error[false_negative] = [40, 90, 230]

    return error


def resize_to_match(
    image: np.ndarray,
    reference: np.ndarray,
    nearest: bool,
) -> np.ndarray:
    if image.shape[:2] == reference.shape[:2]:
        return image

    resampling = (
        Image.Resampling.NEAREST
        if nearest
        else Image.Resampling.LANCZOS
    )

    resized = Image.fromarray(image).resize(
        (reference.shape[1], reference.shape[0]),
        resample=resampling,
    )

    return np.asarray(resized)


def validate_consistency(
    baseline128: ExtractedComparison,
    baseline256: ExtractedComparison,
    topology: ExtractedComparison,
    dataset: str,
) -> None:
    """
    Warn when original images or labels do not appear to represent the same case.
    """
    reference_fundus = baseline128.fundus
    reference_gt = baseline128.ground_truth

    comparison_fundus = resize_to_match(
        baseline256.fundus,
        reference_fundus,
        nearest=False,
    )
    topology_fundus = resize_to_match(
        topology.fundus,
        reference_fundus,
        nearest=False,
    )

    comparison_gt = resize_to_match(
        baseline256.ground_truth,
        reference_gt,
        nearest=True,
    )
    topology_gt = resize_to_match(
        topology.ground_truth,
        reference_gt,
        nearest=True,
    )

    fundus_difference_256 = np.mean(
        np.abs(
            reference_fundus.astype(np.float32)
            - comparison_fundus.astype(np.float32)
        )
    )
    fundus_difference_topology = np.mean(
        np.abs(
            reference_fundus.astype(np.float32)
            - topology_fundus.astype(np.float32)
        )
    )

    gt_difference_256 = np.mean(
        np.abs(
            reference_gt.astype(np.float32)
            - comparison_gt.astype(np.float32)
        )
    )
    gt_difference_topology = np.mean(
        np.abs(
            reference_gt.astype(np.float32)
            - topology_gt.astype(np.float32)
        )
    )

    if (
        fundus_difference_256 > 5.0
        or fundus_difference_topology > 5.0
        or gt_difference_256 > 5.0
        or gt_difference_topology > 5.0
    ):
        print(
            f"WARNING: The files selected for {dataset} may not be the "
            f"same test image across all three models."
        )


def add_error_legend(
    figure: plt.Figure,
) -> None:
    legend_axis = figure.add_axes([0.29, 0.015, 0.42, 0.025])
    legend_axis.axis("off")

    labels = [
        ("True positive", [0, 210, 0]),
        ("False positive", [230, 40, 40]),
        ("False negative", [40, 90, 230]),
    ]

    x_positions = [0.02, 0.37, 0.72]

    for x, (label, rgb) in zip(x_positions, labels):
        legend_axis.add_patch(
            plt.Rectangle(
                (x, 0.18),
                0.045,
                0.60,
                transform=legend_axis.transAxes,
                facecolor=np.asarray(rgb) / 255.0,
                edgecolor="black",
                linewidth=0.6,
            )
        )
        legend_axis.text(
            x + 0.06,
            0.48,
            label,
            transform=legend_axis.transAxes,
            va="center",
            ha="left",
            fontsize=8.5,
        )


def create_qualitative_figure(
    cases: Sequence[CaseSpecification],
    output_dir: Path,
    threshold: int,
    title: str,
) -> tuple[Path, Path, Path]:
    if not 0 <= threshold <= 255:
        raise ValueError("threshold must be in the range 0-255.")

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    rows = len(cases)
    columns = 7

    figure_width = 16.2
    figure_height = max(3.0 * rows + 1.0, 7.0)

    figure, axes = plt.subplots(
        rows,
        columns,
        figsize=(figure_width, figure_height),
        squeeze=False,
    )

    column_titles = [
        "Fundus image",
        "Ground truth",
        "Baseline-128",
        "Baseline-256",
        "Proposed Topology-256",
        "Proposed error map",
        "Topology overlay",
    ]

    for column_index, column_title in enumerate(column_titles):
        axes[0, column_index].set_title(
            column_title,
            fontsize=11,
            fontweight="bold",
            pad=10,
        )

    for row_index, case in enumerate(cases):
        baseline128_path = resolve_case_file(
            case.baseline128_dir,
            case.case_id,
        )
        baseline256_path = resolve_case_file(
            case.baseline256_dir,
            case.case_id,
        )
        topology_path = resolve_case_file(
            case.topology_dir,
            case.case_id,
        )

        baseline128 = extract_four_panel_strip(
            baseline128_path
        )
        baseline256 = extract_four_panel_strip(
            baseline256_path
        )
        topology = extract_four_panel_strip(
            topology_path
        )

        validate_consistency(
            baseline128=baseline128,
            baseline256=baseline256,
            topology=topology,
            dataset=case.dataset,
        )

        reference = baseline128.ground_truth

        baseline128_prediction = resize_to_match(
            baseline128.prediction,
            reference,
            nearest=True,
        )
        baseline256_prediction = resize_to_match(
            baseline256.prediction,
            reference,
            nearest=True,
        )
        topology_prediction = resize_to_match(
            topology.prediction,
            reference,
            nearest=True,
        )

        fundus = resize_to_match(
            baseline128.fundus,
            reference,
            nearest=False,
        )
        ground_truth = reference

        error_map = create_error_map(
            ground_truth=ground_truth,
            prediction=topology_prediction,
            threshold=threshold,
        )

        topology_mask = to_binary_mask(
            topology_prediction,
            threshold,
        )

        topology_overlay = fundus.copy()
        topology_overlay = (
            0.72 * topology_overlay.astype(np.float32)
        )
        overlay_color = np.zeros_like(
            topology_overlay,
            dtype=np.float32,
        )
        overlay_color[..., 1] = 255.0
        topology_overlay[topology_mask] = (
            0.45 * topology_overlay[topology_mask]
            + 0.55 * overlay_color[topology_mask]
        )
        topology_overlay = np.clip(
            topology_overlay,
            0,
            255,
        ).astype(np.uint8)

        images = [
            fundus,
            ground_truth,
            baseline128_prediction,
            baseline256_prediction,
            topology_prediction,
            error_map,
            topology_overlay,
        ]

        for column_index, image in enumerate(images):
            axis = axes[row_index, column_index]
            axis.imshow(image)
            axis.set_xticks([])
            axis.set_yticks([])

            for spine in axis.spines.values():
                spine.set_visible(True)
                spine.set_linewidth(0.6)
                spine.set_edgecolor("0.25")

        axes[row_index, 0].set_ylabel(
            case.dataset,
            fontsize=11,
            fontweight="bold",
            rotation=90,
            labelpad=10,
        )

        axes[row_index, 0].text(
            0.02,
            0.03,
            f"Case {case.case_id}",
            transform=axes[row_index, 0].transAxes,
            fontsize=8,
            color="white",
            bbox={
                "boxstyle": "round,pad=0.2",
                "facecolor": "black",
                "alpha": 0.65,
                "edgecolor": "none",
            },
        )

    figure.suptitle(
        title,
        fontsize=15,
        fontweight="bold",
        y=0.995,
    )

    figure.subplots_adjust(
        left=0.045,
        right=0.995,
        top=0.94,
        bottom=0.065,
        wspace=0.025,
        hspace=0.08,
    )

    add_error_legend(figure)

    png_path = output_dir / "figure_2_qualitative_comparison.png"
    pdf_path = output_dir / "figure_2_qualitative_comparison.pdf"
    svg_path = output_dir / "figure_2_qualitative_comparison.svg"

    figure.savefig(
        png_path,
        dpi=600,
        bbox_inches="tight",
        pad_inches=0.04,
    )
    figure.savefig(
        pdf_path,
        bbox_inches="tight",
        pad_inches=0.04,
    )
    figure.savefig(
        svg_path,
        bbox_inches="tight",
        pad_inches=0.04,
    )

    plt.close(figure)

    return png_path, pdf_path, svg_path


def main() -> None:
    arguments = parse_arguments()

    cases = [
        CaseSpecification(
            dataset=entry[0],
            case_id=entry[1],
            baseline128_dir=Path(entry[2]),
            baseline256_dir=Path(entry[3]),
            topology_dir=Path(entry[4]),
        )
        for entry in arguments.case
    ]

    png_path, pdf_path, svg_path = create_qualitative_figure(
        cases=cases,
        output_dir=arguments.output_dir,
        threshold=arguments.threshold,
        title=arguments.title,
    )

    print("=" * 72)
    print("Qualitative comparison figure created successfully.")
    print("=" * 72)
    print(f"PNG: {png_path.resolve()}")
    print(f"PDF: {pdf_path.resolve()}")
    print(f"SVG: {svg_path.resolve()}")


if __name__ == "__main__":
    main()